In [ ]:
beras = 11400
minyak = 12700
ayam = 3400

print("balanjaan tia")
beras_tia = 10
ayam_tia = 3
jb_tia = (beras_tia * beras) + (ayam_tia * (ayam * 10))
diskon = 90 #kebalikan nya
jb_diskon_tia = (jb_tia / 100) * diskon
print("maka jumlah belanjaan tia " + str(jb_tia) + " rupiah")
print("maka jumlah belanjaan tia setelah diskon adalah " + str(jb_diskon_tia))
print("===belanjaan hana===")
minyak_hana = 2
ayam_hana = 18
diskon = 90 #kebalikan nya
jb_diskon_hana = (jb_tia / 100) * diskon
jb_hana = (minyak_hana * minyak) + (ayam_hana * ayam)
print("maka jumlah belanjaan hana " + str(jb_hana) + " rupiah")
print("maka jumlah belanjaan hana setelah diskon adalah " + str(jb_diskon_hana))

print("belanjaan widia")
beras_widia = 3
minyak_widia = 6
jb_widia = (beras_widia * beras) + (minyak * minyak_widia)
print("maka jumlah belanjaan widia " + str(jb_widia) + " rupiah")

balanjaan tia
maka jumlah belanjaan tia 216000 rupiah
maka jumlah belanjaan tia setelah diskon adalah 194400.0
===belanjaan hana===
maka jumlah belanjaan hana 86600 rupiah
maka jumlah belanjaan hana setelah diskon adalah 194400.0
belanjaan widia
maka jumlah belanjaan widia 110400 rupiah

In [ ]:
		
beras	= 11400	
minyak = 	12700
ayam =	3400	
telur = 	21800	
popok	= 27000	
sabun_cuci = 	1800	
buah_anggur	= 3800	
roti_tawar	= 8500	
tissu =	6400	
mie_instan =	2200	
print("belanjaan tia")
beras_tia = 4
ayam_tia = 2
telur_tia = 3
sabun_cuci_tia = 5
buah_anggur_tia = 4
roti_tawar_tia = 2
mie_instan_tia = 12


diskon = 85
jb_diskon_tia = (jb_tia / 100) * diskon
jb_tia = (beras_tia * beras) + (ayam_tia * (ayam * 10 )) + (telur_tia * telur) + (sabun_cuci_tia * sabun_cuci) + (buah_anggur_tia * buah_anggur ) + (roti_tawar_tia * roti_tawar) + (mie_instan_tia * mie_instan)
print("maka jumlah belanjaan tia " + str(jb_tia) + " rupiah")
print("maka jumlah belanjaan tia setelah diskon adalah " + str(jb_diskon_tia))

print("")
print("")
print("belanjaan hana")
minyak_hana = 2
ayam_hana = 5
telur_hana = 1.5
sabun_cuci_hana = 3
buah_anggur_hana = 8
roti_tawar_hana = 3
tissu_hana = 2
mie_instan_hana = 20


diskon = 90
jb_diskon_hana = (jb_hana / 100) * diskon
jb_hana = (minyak_hana * minyak) + (ayam_hana * ayam ) + (telur_hana * telur ) + (sabun_cuci_hana * sabun_cuci) + (buah_anggur_hana * buah_anggur) + (roti_tawar_hana * roti_tawar) + (tissu_hana * tissu) + (mie_instan_hana * mie_instan)
print("maka jumlah belanjaan hana " + str(jb_hana))
print("maka jumlah belanjaan hana setelah diskon adalah " + str(jb_diskon_hana))

print("")
print("")
print("===belanjaan widia===")
beras_widia = 1
minyak_widia = 1
telur_widia = 1
buah_anggur_widia = 5
tissu_widia = 3
mie_instan_widia = 16


jb_widia = (beras_widia * beras) + (minyak_widia * minyak) + (telur_widia * telur) + (buah_anggur_widia * buah_anggur) + (tissu_widia * tissu) + (mie_instan_widia * mie_instan)
print("maka jumlah belanjaan widia " + str(jb_widia))
print("")
print("")
print("===belanjaan romi===")
minyak_romi = 3
telur_romi = 2
popok_romi = 4
sabun_cuci_romi = 8
mie_instan_romi = 8

diskon = 85
jb_diskon_romi = (jb_romi / 100) * diskon
jb_romi = (minyak_romi * minyak) + (telur_romi * telur) + (popok_romi * popok) + (sabun_cuci_romi * sabun_cuci) + (mie_instan_romi * mie_instan)
print("maka jumlah belanjaan romi " + str(jb_romi))
print("maka jumlah belanjaan romi setelah diskon adalah " + str(jb_diskon_romi))
print("")
print("")
print("===belanjaan samsul===")
ayam_samsul = 3
telur_samsul = 4
popok_samsul = 2
buah_anggur_samsul = 7
tissu_samsul = 5
mie_instan_samsul = 10

diskon = 75
jb_diskon_samsul = (jb_samsul / 100) * diskon
jb_samsul = (ayam_samsul * (ayam * 10)) + (telur_samsul * telur) + (popok_samsul * popok) + (buah_anggur_samsul * buah_anggur) + (tissu_samsul * tissu) + (mie_instan_samsul * mie_instan)
print("maka jumlah belanjaan samsul " + str(jb_samsul))
print("maka jumlah belanjaan samsul setelah diskon adalah " + str(jb_diskon_samsul))
print("")
print("")
print("===belanjaan dimas===")
ayam_dimas = 5
popok_dimas = 5
sabun_cuci_dimas = 4
buah_anggur_dimas = 3
roti_tawar_dimas = 5
mie_instan_dimas = 6

diskon = 75
jb_diskon_dimas = (jb_dimas / 100) * diskon
jb_dimas = (ayam_dimas * (ayam * 10)) + (popok_dimas * popok) + (sabun_cuci_dimas * sabun_cuci) + (buah_anggur_dimas * buah_anggur) + (roti_tawar_dimas * roti_tawar) + (mie_instan_dimas * mie_instan)
print("maka jumlah belanjaan dimas  " + str(jb_dimas))
print("maka jumlah belanjaan dimas setelah diskon adalah " + str(jb_diskon_dimas))

print("")
print("")

max = [284475]
print("Maka jumlah belanjaan paling besar setelah diskon adalah Dimas Rp. " + str(max))
print("======================")
print("")

tenpersen = ("Hana : Rp. 173880")
print("Maka yang mendapat diskon 10 % adalah : " + str(tenpersen))

belanjaan tia
maka jumlah belanjaan tia 246600 rupiah
maka jumlah belanjaan tia setelah diskon adalah 209610.0


belanjaan hana
maka jumlah belanjaan hana 193200.0
maka jumlah belanjaan hana setelah diskon adalah 173880.0


===belanjaan widia===
maka jumlah belanjaan widia 119300


===belanjaan romi===
maka jumlah belanjaan romi 221700
maka jumlah belanjaan romi setelah diskon adalah 188445.0


===belanjaan samsul===
maka jumlah belanjaan samsul 323800
maka jumlah belanjaan samsul setelah diskon adalah 242850.0


===belanjaan dimas===
maka jumlah belanjaan dimas  379300
maka jumlah belanjaan dimas setelah diskon adalah 284475.0


Maka jumlah belanjaan paling besar setelah diskon adalah Dimas Rp. [284475]
======================

Maka yang mendapat diskon 10 % adalah : Hana : Rp. 173880